### ISSUE TITLE
I can't use multiple masternode service in the same address with different port

### ISSUE THREAD

**Issue by tommasomarchionni** [blocknodetech/blocknode#4]
In your homepage there is this FAQ:
"Can I run several nodes on one single VPS?
You can, but you will need to have several ports available. Also, you will need one port for every node, one data directory for every node and to bind=(port) in config along with increased hardware specifications."
If i run Blocknode Core Wallet with masternode.conf with masternode configured with a port different from 37001, i receive this error on wallet startup and then close:
Error reading masternode configuration file: Invalid port detected in masternode.conf
Line: 5
"{mnname} {mnaddress}:50001 {masternodegenkey} {txhash} {outputidx}"
(must be 37001 for mainnet)

**Comment by blocknodetech** [comment]
Thanks for bringing this to our attention - it is an error in our documentation which we will update - you can only run one masternode per VPS.

**Comment by trubus86** [comment]
create wallet ERC.20 or why???
